// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Japuacu.Blog.Negocio.Modelos
{
    public partial class Autor : EntidadeModelo
    {
        public Autor()
        {
            Post = new HashSet<Post>();
        }

        public int Id { get; set; }
        public string Cpf { get; set; }
        public string Nome { get; set; }
        public string Credenciais { get; set; }

        public virtual ICollection<Post> Post { get; set; }
    }
}