// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Japuacu.Blog.Negocio.Modelos
{
    public partial class Paragrafo : EntidadeModelo
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public int Ordem { get; set; }
        public string Redacao { get; set; }

        public virtual Post Post { get; set; }
    }
}