// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Japuacu.Blog.Negocio.Modelos
{
    public partial class Post : EntidadeModelo
    {
        public Post()
        {
            Comentario = new HashSet<Comentario>();
            Paragrafo = new HashSet<Paragrafo>();
        }

        public int Id { get; set; }
        public DateTime DataPost { get; set; }
        public int AutorId { get; set; }
        public string TituloPost { get; set; }
        public string ResumoPost { get; set; }
        public string ImagemPost { get; set; }
        public bool Terminado { get; set; }

        public virtual Autor Autor { get; set; }
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual ICollection<Paragrafo> Paragrafo { get; set; }
    }
}